solarData/config/routes.rb
# Rails.application.reload_routes!
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/'  => 'welcome#index'
  get '/index' => 'welcome#index'
  get '/about' => 'welcome#about'
  get '/contact' => 'welcome#index'
  get '/icons' => 'welcome#index'
  get '/products' => 'welcome#index'
  get '/services' => 'welcome#index'
  get '/typo' => 'welcome#index'

  get 'graphics/show'

  get 'graphics/submit'
  get 'radiations/buscar'
  get 'radiations/energia'
  get 'radiations/calcular'
  resources :radiations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

solarData/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

solarData/app/models/radiation.rb
class Radiation < ApplicationRecord

  scope :created_between, lambda {|start_date, end_date| where("rad_time >= ? AND rad_time <= ?", start_date, end_date )}
  scope :created_between_est, lambda {|start_date, end_date,estacion| where("rad_time >= ? AND rad_time <= ? AND station = ? ", start_date, end_date,estacion)}
end

solarData/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

solarData/app/controllers/graphics_controller.rb
class GraphicsController < ApplicationController
  def show
  end

  def submit
    @start_date = date_params[:start_date]
    @end_date = date_params[:end_date]

    @date = [['Date', 'Radiation']]
    # ['2017-07-19 11:05:00',  3],['2017-07-19 11:20:00',  18],['2017-07-19 11:35:00',  35],['2017-07-19 11:50:00',  137]

    rad = Radiation.created_between(@start_date,@end_date)
    rad.each { |r| @date << [r.rad_time,r.radiation_value]}
    gon.date =@date
  end

  private

  def date_params
    params.permit(:start_date, :end_date)
  end
end

solarData/app/controllers/radiations_controller.rb
class RadiationsController < ApplicationController
  before_action :set_radiation, only: [:show, :edit, :update, :destroy]

  # GET /radiations
  # GET /radiations.json
  def index
    @radiations = Radiation.take(10)
  end

  def buscar
    start = Date.strptime(busqueda_params[:start_date], "%m/%d/%Y")
    end_date = Date.strptime(busqueda_params[:end_date], "%m/%d/%Y")
    estacion = busqueda_params[:estacion]
    @radiations = Radiation.created_between_est(start, end_date,estacion)
    @date = [['Date', 'Radiation']]
    # ['2017-07-19 11:05:00',  3],['2017-07-19 11:20:00',  18],['2017-07-19 11:35:00',  35],['2017-07-19 11:50:00',  137]

    rad = Radiation.created_between_est(start, end_date,estacion)
    rad.each { |r| @date << [r.rad_time,r.radiation_value]}
    gon.date =@date
  end

  def energia

  end

  def calcular
    start = Date.strptime(calcular_params[:start_date], "%m/%d/%Y")
    end_date = Date.strptime(calcular_params[:end_date], "%m/%d/%Y")
    rad = Radiation.created_between_est(start, end_date,1)
    sum = 0
    rad.each { |r| sum += r.radiation_value.to_f*15}
    @energia = (sum*calcular_params[:area].to_f*0.15).to_i/100  
  end

  # GET /radiations/1
  # GET /radiations/1.json
  def show
  end

  # GET /radiations/new
  def new
    @radiation = Radiation.new
  end

  # GET /radiations/1/edit
  def edit
  end

  # POST /radiations
  # POST /radiations.json
  def create
    @radiation = Radiation.new(radiation_params)

    respond_to do |format|
      if @radiation.save
        format.html { redirect_to @radiation, notice: 'Radiation was successfully created.' }
        format.json { render :show, status: :created, location: @radiation }
      else
        format.html { render :new }
        format.json { render json: @radiation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /radiations/1
  # PATCH/PUT /radiations/1.json
  def update
    respond_to do |format|
      if @radiation.update(radiation_params)
        format.html { redirect_to @radiation, notice: 'Radiation was successfully updated.' }
        format.json { render :show, status: :ok, location: @radiation }
      else
        format.html { render :edit }
        format.json { render json: @radiation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /radiations/1
  # DELETE /radiations/1.json
  def destroy
    @radiation.destroy
    respond_to do |format|
      format.html { redirect_to radiations_url, notice: 'Radiation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_radiation
      @radiation = Radiation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def radiation_params
      params.require(:radiation).permit(:station, :name, :rad_time, :radiation_value)
    end

    def busqueda_params
      params.permit(:start_date,:end_date,:estacion)
    end

    def calcular_params
      params.permit(:start_date,:end_date,:area,:rendimiento, :lat, :lon)
    end

end

solarData/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

end

solarData/app/helpers/application_helper.rb
module ApplicationHelper
end

solarData/app/helpers/graphics_helper.rb
module GraphicsHelper
end

solarData/app/helpers/radiations_helper.rb
module RadiationsHelper
end

solarData/app/helpers/welcome_helper.rb
module WelcomeHelper
end

solarData/app/views/graphics/show.html.erb
<h1>Graphics#show</h1>
<p>Find me in app/views/graphics/show.html.erb</p>


<form action="/graphics/submit">
  inicial: <input type="datetime-local" name="start_date"><br>
  final:  <input type="datetime-local" name="end_date"><br>
  <input type="submit" value="Submit">
</form>

solarData/app/views/graphics/submit.html.erb
<%= include_gon %>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable(gon.date);

        var options = {
          title: 'Comportamiento de la radiación',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="curve_chart" style="width: 1500px; height: 500px"></div>
    <%=@date%>
  </body>

solarData/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Radiación Valle de Aburrá</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Solar Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
    Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //meta tags -->
    <!--fonts-->
    <link href="//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <!--//fonts-->

    <!-- Required-js -->

    <!-- main slider-banner -->

    <script type="text/javascript">
    		jQuery(document).on('turbolinks:load', function() {
    			jQuery('#demo1').skdslider({'delay':5000, 'animationSpeed': 2000,'showNextPrev':true,'showPlayButton':true,'autoSlide':true,'animationType':'fading'});

    			jQuery('#responsive').change(function(){
    			  $('#responsive_wrapper').width(jQuery(this).val());
    			});

    		});
    </script>
    <!-- //main slider-banner -->

    <!-- scriptfor smooth drop down-nav -->
    <script>
    $(document).on('turbolinks:load', function() {
        $(".dropdown").hover(
            function() {
                $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
                $(this).toggleClass('open');
            },
            function() {
                $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
                $(this).toggleClass('open');
            }
        );
    });
    </script>
    <!-- //script for smooth drop down-nav -->

</head>

  <body>
    <%=render "partials/header"%>
    <%= yield %>
    <%=render "partials/footer"%>
  </body>
</html>

solarData/app/views/partials/_cifras.html.erb
<!--stats-->
<div class="stats" id="stats">
  <div class="container">
    <div class="stats-info">
      <div class="col-md-4 col-sm-4 stats-grid slideanim">
        <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='1200' data-delay='.5' data-increment="1">1200</div>
        <h4 class="stats-info">Imagenes satelitales</h4>
      </div>
      <div class="col-md-4 col-sm-4 stats-grid slideanim">
        <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='3000' data-delay='.5' data-increment="1">3000</div>
        <h4 class="stats-info">Datos del SIATA</h4>
      </div>
      <div class="col-md-4 col-sm-4 stats-grid slideanim">
        <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='3' data-delay='.9' data-increment="1">3</div>
        <h4 class="stats-info">Estaciones de medición</h4>
      </div>

      <div class="clearfix"></div>
    </div>
  </div>
</div>
<!--//stats-->

solarData/app/views/partials/_footer.html.erb
<div class="footer-top">
	<div class="container">
		<div class="col-sm-6 w3ls-footer-top">
			<h3>QUICK <span>LINKS</span></h3>
				<ul>
						<li><a href="/">Inicio</a></li>
						<li><a href="/radiations">Radiación</a></li>
						<li><a href="/services">Energía</a></li>
						<li><a href="/products">Prediciones</a></li>
						<li><a href="/about">Acerca de</a></li>
					</ul>
		</div>
		<div class="col-sm-6 wthree-footer-top">
			<h3>DIR<span>ECIÓN</span></h3>
				<ul>
				<li><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Carrera 49 # 7 sur 50. Medellín, Antioquia</li>
				<li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href="mailto:info@example.com">info@example.com</a></li>
				<li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> (57) (4) 261 9500</li>
			</ul>
		</div>


			<div class="clearfix"></div>

		<div class="footer-w3layouts">
			<div class="agile-copy">
				<p>© 2017 Solar Panel. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
			</div>
		</div>
	</div>
</div>

solarData/app/views/partials/_header.html.erb
<!-- header -->
<header>
  <!-- Top part: Logo y nombre del proyecto -->
	<div class="w3layouts-top-strip">
		<div class="container">
			<div class="logo">
				<h1><a href="index.html"><span>Radiación </span>Valle de Aburrá</a></h1>
			</div>

			<div class="agileits-contact-info text-right">
				<ul>
					<li><span>YAMPL</span> Yet another machine learning project</li>
				</ul>
			</div>

			<div class="clearfix"></div>
		</div>
	</div>

	<!-- navigation -->
		<nav class="navbar navbar-default">
		  <div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			  <ul class="nav navbar-nav">
				<li><a class="active" href="/">Inicio</a></li>
				<li><a href="/radiations">Radiación</a></li>
				<li><a href="/radiations/energia">Energía</a></li>
				<li><a href="/products">Prediciones</a></li>
				<li class="dropdown">
				  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Info <span class="caret"></span></a>
				  <ul class="dropdown-menu">
          <li><a href="/about">Acerca de</a></li>
				  <li><a href="/icons">Icons Page</a></li>
					<li><a href="/typo">Typography</a></li>

				  </ul>
				</li>
			  </ul>
			</div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
	<!-- //navigation -->
</header>
<!-- //header -->

solarData/app/views/radiations/_busqueda.html.erb
<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker();
    });
    $(function () {
        $('#datetimepicker2').datetimepicker();
    });
</script>
<form action="/radiations/buscar">
<div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <label for="">Buscar desde:</label>
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" name="start_date"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>

            <div class="form-group">
                <label for="">Hasta:</label>
                <div class='input-group date' id='datetimepicker2'>
                    <input type='text' class="form-control" name="end_date" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>

            <div class="form-group">
                <label for="">Estación:</label>
                <label class="radio-inline"><input type="radio" name="estacion" value="1">1</label>
                <label class="radio-inline"><input type="radio" name="estacion" value="2">2</label>
                <label class="radio-inline"><input type="radio" name="estacion" value="3">3</label>
                </div>
            </div>

        </div>
        <input type="submit" value="Buscar" class="btn">
    </div>
</form>

<input name="searchTxt" type="text" maxlength="512" id="searchTxt" class="searchField"/>

<script>
    var input = document.getElementById("searchTxt");

    function searchURL() {
         window.location = "http://www.myurl.com/search/" + input.value;
    }
</script>

solarData/app/views/radiations/_form.html.erb
<%= form_with(model: radiation, local: true) do |form| %>
  <% if radiation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(radiation.errors.count, "error") %> prohibited this radiation from being saved:</h2>

      <ul>
      <% radiation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :station %>
    <%= form.text_field :station, id: :radiation_station %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :radiation_name %>
  </div>

  <div class="field">
    <%= form.label :rad_time %>
    <%= form.date_select :rad_time, id: :radiation_rad_time %>
  </div>

  <div class="field">
    <%= form.label :radiation_value %>
    <%= form.text_field :radiation_value, id: :radiation_radiation_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

solarData/app/views/radiations/buscar.html.erb
<%= include_gon %>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable(gon.date);

        var options = {
          title: 'Comportamiento de la radiación',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }
    </script>

<div class="container">
  <h2 class="w3ls_head">Bus<span>queda</span></h2>

  <div id="curve_chart" style="width:auto; height: 500px"></div>

  <table id="customers">
    <thead>
      <tr>
        <th>Estación</th>
        <th>Hora de captura</th>
        <th>Valor de la radiacón</th>
      </tr>
    </thead>

    <tbody>
      <% @radiations.each do |radiation| %>
        <tr>
          <td><%= radiation.station %></td>
          <td><%= radiation.rad_time.localtime %></td>
          <td><%= radiation.radiation_value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

solarData/app/views/radiations/calcular.html.erb
<div class="stats" id="stats">
  <div class="container shadowbox1">
    <div class="stats-info">

      <div class="col-md-4 col-sm-4 stats-grid slideanim">
        <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='<%=@energia%>' data-delay='.9' data-increment="10"><%=@energia%></div>
        <h4 class="stats-info">Energia esperada en Watts</h4>
      </div>

      <div class="clearfix"></div>
    </div>
  </div>
</div>

solarData/app/views/radiations/edit.html.erb
<h1>Editing Radiation</h1>

<%= render 'form', radiation: @radiation %>

<%= link_to 'Show', @radiation %> |
<%= link_to 'Back', radiations_path %>

solarData/app/views/radiations/energia.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<script>
var x = document.getElementById("demo");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPosition(position) {
    x.innerHTML = "Latitude: " + position.coords.latitude +
    "<br>Longitude: " + position.coords.longitude;
}



</script>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker3').datetimepicker();
    });
    $(function () {
        $('#datetimepicker4').datetimepicker();
    });
</script>

<div class="clearfix"></div>
<div class="stats" id="stats">
  <div class="container">
  </div>
</div>


  <div class="container">
    <h2 class="w3ls_head">Ene<span>rgía</span></h2>
    <p>Para hacer un mejor calculo de cuanta energía se</p>
    <p>generó en dias pasados cerca al lugar en donde</p>
    <p>tienes el panel solar, es necesario que nos brindes</p>
    <p>tu ubicación y la agregues al siguiente formulario.</p>
    <button onclick="getLocation()" class="btn">Conocer ubicación</button>
    <p id="demo"></p>
  </div>

<form action="/radiations/calcular">

  <div class="container shadowbox">
    <p>(en esta fase beta podras encontrar información desde: 2017-07-19 hasta: 2017-10-27)</p>
    <label for="fname">Latitud</label>
    <input type="text"  name="lat" >

    <label for="lname">Longitud</label>
    <input type="text"  name="long">

    <label for="lname">Área del panel m<sup>2</sup></label>
    <input type="text"  name="area">

    <label for="lname">Rendimiento del panel</label>
    <input type="text"  name="rendimiento">

    <label for="lname">Desde</label>
    <div class="form-group">
    <div class='input-group date' id='datetimepicker3'>
        <input type='text' class="form-control" name="start_date"/>
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>
    </div>


    <label for="lname">Hasta</label>
    <div class="form-group">
    <div class='input-group date' id='datetimepicker4'>
        <input type='text' class="form-control" name="end_date"/>
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>
    </div>

    <input type="submit" value="Calcular" class="btn">

  </div>

</form>

solarData/app/views/radiations/index.html.erb
<p id="notice"><%= notice %></p>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

<div class="clearfix"></div>
<div class="w3layouts-clients">
  <div class="container"></div>
</div>
  <div class="container">
    <h2 class="w3ls_head">Rad<span>iaciones</span></h2>
    <p>En este lugar puedes consultar como se ha comportado la radición en fechas pasadas.
    (en esta fase beta podras encontrar información desde: 2017-07-19 hasta: 2017-10-27) </p>
    <div class="clearfix"></div>
    

    <%= render 'busqueda' %>

    <table id="customers">
      <thead>
        <tr>
          <th>Estación</th>
          <th>Hora de captura</th>
          <th>Valor de la radiacón</th>
        </tr>
      </thead>

      <tbody>
        <% @radiations.each do |radiation| %>
          <tr>
            <td><%= radiation.station %></td>
            <td><%= radiation.rad_time.localtime %></td>
            <td><%= radiation.radiation_value %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="clearfix"></div>
<br>

solarData/app/views/radiations/new.html.erb
<h1>New Radiation</h1>

<%= render 'form', radiation: @radiation %>

<%= link_to 'Back', radiations_path %>

solarData/app/views/radiations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station:</strong>
  <%= @radiation.station %>
</p>

<p>
  <strong>Name:</strong>
  <%= @radiation.name %>
</p>

<p>
  <strong>Rad time:</strong>
  <%= @radiation.rad_time %>
</p>

<p>
  <strong>Radiation value:</strong>
  <%= @radiation.radiation_value %>
</p>

<%= link_to 'Edit', edit_radiation_path(@radiation) %> |
<%= link_to 'Back', radiations_path %>

solarData/app/views/welcome/about.html.erb
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->

	<!-- banner -->
	<div class="agile-banner">
	</div>
	<!-- //banner -->
<!-- about -->
	<div class="services-w3ls">
		<div class="container">
			<h2 class="w3ls_head">Acerca de <span>Nosotros</span></h2>
			<div class="agile_banner_bottom_grids">
				<div class="col-md-6 w3layouts_about_grid_left">
					<h4>About Solar Energy</h4>
					<p>Cras molestie lacus et libero vehicula semper. Pellentesque ac leo quis enim
						ultrices mollis. Duis ornare in dolor non ultricies. Integer nec sem diam.
						In sed urna at mi fringilla malesuada.
						<i>"Aenean efficitur vitae ligula eget vulputate.
						Donec id ligula lorem. Nam ipsum odio, rutrum a nisl non, scelerisque iaculis ex.</i>
						Integer mattis efficitur scelerisque. Phasellus malesuada metus vitae orci condimentum,
						non blandit lacus consectetur. </p>
				</div>
				<div class="col-md-6 w3layouts_about_grid_right">
					<iframe src="https://player.vimeo.com/video/25401444"></iframe>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //about -->
<!--stats-->
<%=render "partials/cifras"%>
<!--//stats-->

<!-- team -->
	<div class="services team">
		<div class="container">
			<h3 class="w3ls_head">Meet <span>Our Team</span></h3>
			<div class="agile_banner_bottom_grids">
				<div class="col-md-3 agile_team_grid">
					<div class="agileits_w3layouts_team_grid">
            <%= image_tag("t1.jpg", :class => "img-responsive") %>
						<div class="agileits_w3layouts_team_grid_pos">
							<div class="w3ls-social">
								<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
								<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
								<a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a>
								<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
							</div>
						</div>
					</div>
					<h4>Williamson</h4>
					<p>Designer</p>
				</div>
				<div class="col-md-3 agile_team_grid">
					<div class="agileits_w3layouts_team_grid">
						<%= image_tag("t2.jpg", :class => "img-responsive") %>
						<div class="agileits_w3layouts_team_grid_pos">
							<div class="w3ls-social">
								<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
								<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
								<a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a>
								<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
							</div>
						</div>
					</div>
					<h4>Laura </h4>
					<p>Manager</p>
				</div>
				<div class="col-md-3 agile_team_grid">
					<div class="agileits_w3layouts_team_grid">
						<%= image_tag("t3.jpg", :class => "img-responsive") %>
						<div class="agileits_w3layouts_team_grid_pos">
							<div class="w3ls-social">
								<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
								<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
								<a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a>
								<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
							</div>
						</div>
					</div>
					<h4>Thomas</h4>
					<p>CEO / PHP Developer</p>
				</div>
				<div class="col-md-3 agile_team_grid">
					<div class="agileits_w3layouts_team_grid">
						<%= image_tag("t4.jpg", :class => "img-responsive") %>
						<div class="agileits_w3layouts_team_grid_pos">
							<div class="w3ls-social">
								<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
								<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
								<a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a>
								<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
							</div>
						</div>
					</div>
					<h4>Rosy </h4>
					<p>PHP Developer</p>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!-- //team -->